# theme = "base24"
theme = "dark_plus_plus"

[editor]
line-number = "relative"
shell = ["nu", "-c"]
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "hidden"
  
[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true

[editor.file-picker]
hidden = false

[keys.normal]
q = ":buffer-close"
Q = ":buffer-close!"
z = ":write"
Z = ":write!"
v = "select_mode"
"@" = "record_macro"
"!" = "replay_macro"
N = ":buffer-previous"
H = ":buffer-next"

# movement
y = "move_visual_line_up"
e = "move_char_left"
i = "move_visual_line_down"
o = "move_char_right"
Y = [ "goto_window_top", "move_visual_line_up", "align_view_center" ]
E = "goto_first_nonwhitespace"
I = [ "goto_window_bottom", "move_visual_line_down", "align_view_center" ]
O = "goto_line_end"
w = "move_next_word_end"
W = "move_next_long_word_end"
b = "move_prev_word_start"
B = "move_prev_long_word_start"

# text-manipulation
c = "yank" # copy
C = "yank_to_clipboard" # copy to clipboard
p = "paste_before" # paste
P = "paste_clipboard_before" # paste from clipboard
d = "delete_selection_noyank" # delete selection
x = "delete_selection" # delete and copy selection
X = [ "yank_to_clipboard", "delete_selection_noyank" ] # delete and copy selection to clipboard
R = "replace_with_yanked" # delete selection and paste (replace)
A = "replace_selections_with_clipboard" # delete selection and paste from clipboard (replace with clipboard)
r = "replace" # replace character
a = [ "delete_selection_noyank", "insert_mode" ] # delete selection & insert
"backspace" = [ "move_char_left", "delete_selection_noyank" ]
u = "undo"
U = "redo"
"tab" =	"indent"
"S-tab"	= "unindent"

"+" = "surround_add"
"=" = "surround_replace"
"*" = "surround_delete"
">" = "switch_to_uppercase"
"~" = "switch_case"
"<" = "switch_to_lowercase"

n = [ "collapse_selection", "insert_mode" ]
space.n = "open_above"
h = [ "move_char_right", "insert_mode" ]
space.h = "open_below"
D = "select_register"
V = "match_brackets"
"{" = "expand_selection"
"}" = "shrink_selection"

# find & selection
g = "file_picker" # Fd Search
G = "global_search" # Ripgrep Search
s = "search"
S = [ "search_selection", "search" ]
M = "search_prev" # goto_prev_match
m = "search_next" # goto_next_match
F = "extend_prev_char" # goto_prev_char
f = "extend_next_char" # goto_next_char
T = "extend_till_prev_char" # till_prev_char
t = "extend_till_char" # till_next_char

j = "copy_selection_on_prev_line" # add cursor and selection above
J = [ "add_newline_above", "move_visual_line_up" ]
k = "copy_selection_on_next_line" # add cursor and selection below
K = [ "add_newline_below", "move_visual_line_down" ]
l = "extend_line_below"
L = [ "extend_line_up", "extend_to_line_bounds" ]
"%" = "select_all"
"/" = "select_regex"
"," = "join_selections_space"
";" = "split_selection_on_newline"
# "." = repeat_last_insert
# ":" = command_mode
"'" = "collapse_selection"
"\"" = "flip_selections"
"_" = "keep_primary_selection"
"minus" = "remove_primary_selection"
"(" = "rotate_selections_backward"
")" = "rotate_selections_forward"
"&" = [ "indent", "split_selection_on_newline", "trim_selections", "align_selections", "flip_selections", "delete_selection", "move_char_left", "move_prev_word_start", "replace_with_yanked" ]
# merge_selections
# merge_consecutive_selections

space.y = "goto_file_start"
space.i = "goto_file_end"
space."." = "goto_last_modification"
space.q = ":quit"
space.Q = ":quit!"
space.l = ":lsp-restart"
space.L = ":lsp-stop"
space.o = ":reload-all"
space.O = ":config-reload"
space.t = "align_view_top"
space.m = "align_view_center"
space.b = "align_view_bottom"
space.M = "align_view_middle"
space.c = "toggle_comments"
space.C = "toggle_block_comments"
space.p = "hover" ## Show documentation for item under cursor in a popup (LSP)
space.e = "workspace_diagnostics_picker" ## Open workspace diagnostics picker (LSP)
space.E = "diagnostics_picker" ## Open document diagnostics picker (LSP)
space.d = "goto_definition" ## Go to definition (LSP)
space.D = "goto_type_definition" ## Go to type definition (LSP)
space.s = "symbol_picker" ## Open document symbol picker (LSP)
space.S = "workspace_symbol_picker" ## Open workspace symbol picker (LSP)
space.r = "rename_symbol" ## Rename symbol (LSP)
space.R = "select_references_to_symbol_under_cursor" ## Select symbol references (LSP)
space.a = "code_action" ## Apply code action (LSP)
# space.r = "goto_reference" ## Go to references (LSP)
# space.R = "goto_implementation" ## Go to implementation (LSP)
# space."=" = "format_selections" ## Format selection (currently nonfunctional/disabled) (LSP)
# space.G	## Debug (experimental)
# space.w	## Enter window mode
space.f = [
  ':sh rm -f /tmp/files2open',
  ':set mouse false',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/files2open',
  ':redraw',
  ':set mouse true',
  ':open /tmp/files2open',
  'select_all',
  'split_selection_on_newline',
  'goto_file',
  ':buffer-close! /tmp/files2open',
]

"[".space = "no_op"
"]".space = "no_op"
space.F = "no_op"
space.j = "no_op"
space.g = "no_op"
space."?" = "no_op"
space."'" = "no_op"
space.k = "no_op"
space.Y = "no_op"
space.P = "no_op"
space.A-c = "no_op"
space."/" = "no_op"
"C-i" = "no_op"
"C-o" = "no_op"
"C-s" = "no_op"
"C-b" = "no_op"
"C-f" = "no_op"
"C-d" = "no_op"
"C-u" = "no_op"
"C-w" = "no_op"
# window mode
# insert mode
# picker
# prompt

[keys.select]
q = ":buffer-close"
Q = ":buffer-close!"
z = ":write"
Z = ":write!"
v = "normal_mode"
"@" = "record_macro"
"!" = "replay_macro"
N = ":buffer-previous"
H = ":buffer-next"

# movement
y = "extend_visual_line_up"
e = "extend_char_left"
i = "extend_visual_line_down"
o = "extend_char_right"
Y = [ "goto_window_top", "extend_visual_line_up", "align_view_center" ]
E = "goto_first_nonwhitespace"
I = [ "goto_window_bottom", "extend_visual_line_down", "align_view_center" ]
O = "goto_line_end"
w = "extend_next_word_end"
W = "extend_next_long_word_end"
b = "extend_prev_word_start"
B = "extend_prev_long_word_start"

# text-manipulation
c = "yank" # copy
C = "yank_to_clipboard" # copy to clipboard
p = "paste_before" # paste
P = "paste_clipboard_before" # paste from clipboard
d = "delete_selection_noyank" # delete selection
x = "delete_selection" # delete and copy selection
X = [ "yank_to_clipboard", "delete_selection_noyank" ] # delete and copy selection to clipboard
R = "replace_with_yanked" # delete selection and paste (replace)
A = "replace_selections_with_clipboard" # delete selection and paste from clipboard (replace with clipboard)
r = "replace" # replace character
a = [ "delete_selection_noyank", "insert_mode" ] # delete selection & insert
"backspace" = [ "move_char_left", "delete_selection_noyank" ]
u = "undo"
U = "redo"
"tab" =	"indent"
"S-tab"	= "unindent"

"+" = "surround_add"
"=" = "surround_replace"
"*" = "surround_delete"
">" = "switch_to_uppercase"
"~" = "switch_case"
"<" = "switch_to_lowercase"

space.n = "open_above"
space.h = "open_below"
D = "select_register"
V = "match_brackets"
"{" = "expand_selection"
"}" = "shrink_selection"

# find & selection
g = "file_picker" # Fd Search
G = "global_search" # Ripgrep Search
s = "search"
S = [ "search_selection", "search" ]
M = "search_prev" # goto_prev_match
m = "search_next" # goto_next_match
F = "extend_prev_char" # goto_prev_char
f = "extend_next_char" # goto_next_char
T = "extend_till_prev_char" # till_prev_char
t = "extend_till_char" # till_next_char

n = [ "normal_mode", "select_textobject_inner" ] # match inner
h = [ "normal_mode", "select_textobject_around" ] # match outer
j = "copy_selection_on_prev_line" # add cursor and selection above
J = [ "add_newline_above", "move_visual_line_up" ]
k = "copy_selection_on_next_line" # add cursor and selection below
K = [ "add_newline_below", "move_visual_line_down" ]
l = "extend_line_below"
L = [ "extend_line_up", "extend_to_line_bounds" ]
"%" = "select_all"
"/" = "select_regex"
"," = "join_selections_space"
";" = "split_selection_on_newline"
# "." = repeat_last_insert
# ":" = command_mode
"'" = "collapse_selection"
"\"" = "flip_selections"
"_" = "keep_primary_selection"
"minus" = "remove_primary_selection"
"(" = "rotate_selections_backward"
")" = "rotate_selections_forward"
"&" = [ "indent", "split_selection_on_newline", "trim_selections", "align_selections", "flip_selections", "delete_selection", "move_char_left", "move_prev_word_start", "replace_with_yanked" ]

space.y = "goto_file_start"
space.i = "goto_file_end"
space."." = "goto_last_modification"
space.q = ":quit"
space.Q = ":quit!"
space.l = ":lsp-restart"
space.L = ":lsp-stop"
space.o = ":reload-all"
space.O = ":config-reload"
space.t = "align_view_top"
space.m = "align_view_center"
space.b = "align_view_bottom"
space.M = "align_view_middle"
space.c = "toggle_comments"
space.C = "toggle_block_comments"
space.p = "hover" ## Show documentation for item under cursor in a popup (LSP)
space.e = "workspace_diagnostics_picker" ## Open workspace diagnostics picker (LSP)
space.E = "diagnostics_picker" ## Open document diagnostics picker (LSP)
space.d = "goto_definition" ## Go to definition (LSP)
space.D = "goto_type_definition" ## Go to type definition (LSP)
space.s = "symbol_picker" ## Open document symbol picker (LSP)
space.S = "workspace_symbol_picker" ## Open workspace symbol picker (LSP)
space.r = "rename_symbol" ## Rename symbol (LSP)
space.R = "select_references_to_symbol_under_cursor" ## Select symbol references (LSP)
space.a = "code_action" ## Apply code action (LSP)
# space.r = "goto_reference" ## Go to references (LSP)
# space.R = "goto_implementation" ## Go to implementation (LSP)
# space."=" = "format_selections" ## Format selection (currently nonfunctional/disabled) (LSP)
# space.G	## Debug (experimental)
# space.w	## Enter window mode
space.f = [
  ':sh rm -f /tmp/files2open',
  ':set mouse false',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/files2open',
  ':redraw',
  ':set mouse true',
  ':open /tmp/files2open',
  'select_all',
  'split_selection_on_newline',
  'goto_file',
  ':buffer-close! /tmp/files2open',
]

"[".space = "no_op"
"]".space = "no_op"
space.F = "no_op"
space.j = "no_op"
space.g = "no_op"
space."?" = "no_op"
space."'" = "no_op"
space.k = "no_op"
space.Y = "no_op"
space.P = "no_op"
space.A-c = "no_op"
space."/" = "no_op"
"C-i" = "no_op"
"C-o" = "no_op"
"C-s" = "no_op"
"C-b" = "no_op"
"C-f" = "no_op"
"C-d" = "no_op"
"C-u" = "no_op"
"C-w" = "no_op"
