[mgr]
keymap = [
    { on = "<Esc>",     run = "escape",                      desc = "Exit visual mode, clear selected, or cancel search" },
    { on = "q",         run = "close",                       desc = "Close the current tab, or quit if it is last tab" },
    { on = "Q",         run = "quit",                        desc = "Exit the process" },

  	# Navigation
    { on = "e",              run = "leave",                  desc = "Go back to the parent directory" },
    { on = "o",              run = "enter",                  desc = "Enter the child directory" },
    { on = "y",              run = "arrow -1",               desc = "Move cursor up" },
    { on = "i",              run = "arrow 1",                desc = "Move cursor down" },
    { on = "Y",              run = "arrow -50%",             desc = "Move cursor up half page" },
    { on = "I",              run = "arrow 50%",              desc = "Move cursor down half page" },
    { on = ["<space>", "y"], run = "arrow top",              desc = "Move cursor to the top" },
    { on = ["<space>", "i"], run = "arrow bot",              desc = "Move cursor to the bottom" },
    { on = "E",              run = "seek -8",                desc = "Seek up 8 units in the preview" },
    { on = "O",              run = "seek 8",                 desc = "Seek down 8 units in the preview" },
    { on = "u",              run = "back",                   desc = "Go back to the previous directory" },
    { on = "U",              run = "forward",                desc = "Go forward to the next directory" },

    # Selection
    { on = "l",         run = [ "toggle", "arrow 1" ],       desc = "Toggle the current selection state" },
    { on = "L",         run = [ "toggle", "arrow -1" ],      desc = "Toggle the current selection state" },
    { on = "%",         run = "toggle_all",                  desc = "Select all files" },
    { on = "v",         run = "visual_mode",                 desc = "Enter visual mode (selection mode)" },
    { on = "V",         run = "visual_mode --unset",         desc = "Enter visual mode (unset mode)" },

    # Operation
    { on = "<Enter>",   run = "open",                        desc = "Open selected files" },
    { on = "<S-Enter>", run = "open --interactive",          desc = "Open selected files" },
    { on = "t",         run = "create",                      desc = "Create a file (ends with / for directories)" },
    { on = "r",         run = "rename --empty=stem --cursor=start", desc = "Rename selected file(s)" },
    { on = "R",         run = "rename --cursor=before_ext",  desc = "Rename selected file(s)" },
    { on = "c",         run = "yank",                        desc = "Yank selected files (copy)" },
    { on = "x",         run = "yank --cut",                  desc = "Yank selected files (cut)" },
    { on = "p",         run = "paste",                       desc = "Paste yanked files" },
    { on = "d",         run = "remove",                      desc = "Trash selected files" },
    { on = "k",         run = "unyank",                      desc = "Cancel the yank status" },
    { on = ".",         run = "hidden toggle",               desc = "Toggle the visibility of hidden files" },
    { on = "-",         run = "link",                        desc = "Symlink the absolute path of yanked files" },
    { on = "_",         run = "link --relative",             desc = "Symlink the relative path of yanked files" },

    # Search, Find and Filter
    { on = "m",         run = "find_arrow",                  desc = "Go to the next match" },
    { on = "M",         run = "find_arrow --previous",       desc = "Go to the previous match" },
    { on = "f",         run = "find --smart",                desc = "Find next file" },
    { on = "F",         run = "filter --smart",              desc = "Filter files" },
    { on = "s",         run = "search fd",                   desc = "Search files by name using fd" },
    { on = "S",         run = "search rg",                   desc = "Search files by content using ripgrep" },
    { on = "g",         run = "plugin zoxide",               desc = "Jump to a directory using zoxide" },
    { on = "G",         run = "cd --interactive",            desc = "Interactively move through directories" },

    # Sorting, Linemode and Copy
    { on = ["<space>", "<space>"], run = "spot",                                       desc = "Spot hovered file" },

    { on = ["<space>", "s"], run = [ "sort size --reverse", "linemode size" ],         desc = "Sort by size (decending order)" },
    { on = ["<space>", "S"], run = "linemode size",                                    desc = "Set linemode to size" },

    { on = ["<space>", "m"], run = [ "sort modified --reverse", "linemode mtime" ],    desc = "Sort by last modified time" },
    { on = ["<space>", "M"], run = "linemode mtime",                                   desc = "Set linemode to mtime" },

    { on = ["<space>", "c"], run = [ "sort created --reverse", "linemode ctime" ],     desc = "Sort by last created time" },
    { on = ["<space>", "C"], run = "linemode ctime",                                   desc = "Set linemode to ctime" },

    { on = ["<space>", "n"], run = "sort natural --reverse=no",                        desc = "Sort naturally" },
    { on = ["<space>", "N"], run = "linemode none",                                    desc = "Set linemode to none" },

    { on = ["<space>", "p"], run = "linemode permissions",                             desc = "Set linemode to permissions" },
    { on = ["<space>", "o"], run = "linemode owner",                                   desc = "Set linemode to owner" },

    { on = ["<space>", "e"], run = "sort extension --reverse=no",                      desc = "Sort by extension" },
    { on = ["<space>", "E"], run = "sort extension --reverse",                         desc = "Sort by extension (reverse)" },
    { on = ["<space>", "a"], run = "sort alphabetical --reverse=no",                   desc = "Sort alphabetically" },
    { on = ["<space>", "A"], run = "sort alphabetical --reverse",                      desc = "Sort alphabetically (reverse)" },
    { on = ["<space>", "r"], run = "sort natural --reverse",                           desc = "Sort reverse" },
    { on = ["<space>", "R"], run = "sort random --reverse=no",                         desc = "Sort randomly" },

    { on = ["<space>", "/"], run = "copy path",                                        desc = "Copy the file path" },
    { on = ["<space>", "d"], run = "copy dirname",                                     desc = "Copy the directory path" },
    { on = ["<space>", "f"], run = "copy filename",                                    desc = "Copy the filename" },
    { on = ["<space>", "F"], run = "copy name_without_ext",                            desc = "Copy the filename without extension" },


    { on = "w",              run = "tasks:show",                                       desc = "Show task manager" },
    { on = "$",              run = "shell --interactive",                              desc = "Run a shell command" },
    { on = "W",              run = 'shell --orphan "wset $0"',                         desc = "Sets wallpaper" },
    { on = "~",              run = "help",                                             desc = "Open Help" },

    # { on = "T", run = "tab_create --current",        desc = "Create a new tab with CWD" },
    # { on = "N", run = "tab_switch -1 --relative",    desc = "Switch to the previous tab" },
    # { on = "H", run = "tab_switch 1 --relative",     desc = "Switch to the next tab" },
    # { on = "n", run = "tab_swap -1",                 desc = "Swap current tab with previous tab" },
    # { on = "h", run = "tab_swap 1",                  desc = "Swap current tab with next tab" },
    # { on = "", run = "paste --force", desc = "Paste yanked files (overwrite if the destination exists)" },
    # { on = "", run = "remove --permanently", desc = "Permanently delete selected files" },
    # { on = "", run = "hardlink", desc = "Hardlink yanked files" },

    # { on = "", run = "reveal", desc = "" },
    # { on = "", run = "toggle", desc = "" },
    # { on = "", run = "toggle_all", desc = "" },
    # { on = "", run = "sort", desc = "" },
]

[input]
keymap = [
    { on = "<C-c>",       run = "close",                     desc = "Cancel input" },
    { on = "<Enter>",     run = "close --submit",            desc = "Submit input" },
    { on = "<Esc>",       run = "escape",                    desc = "Go back the normal mode, or cancel input" },

    # Mode
    { on = "n",  run = "insert",                             desc = "Enter insert mode" },
    { on = "h",  run = "insert --append",                    desc = "Enter append mode" },
    { on = "N",  run = [ "move bol", "insert" ],             desc = "Move to the BOL, and enter insert mode" },
    { on = "H",  run = [ "move eol", "insert --append" ],    desc = "Move to the EOL, and enter append mode" },
    { on = "v",  run = "visual",                             desc = "Enter visual mode" },
    { on = "%",  run = [ "move bol", "visual", "move eol" ], desc = "Enter visual mode and select all" },

    # Movement
    { on = "e",           run = "move -1",                   desc = "Move back a character" },
    { on = "o",           run = "move 1",                    desc = "Move forward a character" },
    { on = "E",           run = "move bol",                  desc = "Move to the BOL" },
    { on = "O",           run = "move eol",                  desc = "Move to the EOL" },
    { on = "b",           run = "backward",                  desc = "Move back to the start of the current or previous word" },
    { on = "w",           run = "forward --end-of-word",     desc = "Move forward to the end of the current or next word" },
    #{ on = "",           run = "forward",                   desc = "Move forward to the start of the next word" },

    # Text-Manipulation
    { on = "c",           run = "yank",                      desc = "Copy the selected characters" },
    { on = "p",           run = "paste --before",            desc = "Paste the copied characters before the cursor" },
    { on = "x",           run = "delete --cut",              desc = "Cut the selected characters" },
    { on = "d",           run = "delete",                    desc = "Delete the selected characters" },
    { on = "a",           run = "delete --insert",           desc = "Delete the selected characters, and enter insert mode" },
    { on = "r",           run = "replace",                   desc = "Replace a single character" },
    { on = "<Backspace>", run = "backspace",	               desc = "Delete the character before the cursor" },
    { on = "<Delete>",    run = "backspace --under",         desc = "Delete the character under the cursor" },
    { on = "u",           run = "undo",                      desc = "Undo the last operation" },
    { on = "U",           run = "redo",                      desc = "Redo the last operation" },

    # Kill
    { on = "<A-e>",       run = "kill bol",                  desc = "Kill backwards to the BOL" },
    { on = "<A-o>",       run = "kill eol",                  desc = "Kill forwards to the EOL" },
    { on = "<A-b>",       run = "kill backward",             desc = "Kill backwards to the start of the current word" },
    { on = "<A-w>",       run = "kill forward",              desc = "Kill forwards to the end of the current word" },

    { on = "~",           run = "help",                      desc = "Open Help" },
]

[confirm]
keymap = [
    { on = "<Esc>",       run = "close",                     desc = "Cancel the confirm" },
    { on = "<Enter>",     run = "close --submit",            desc = "Submit the confirm" },
    { on = "E",           run = "arrow prev",                desc = "Move cursor up" },
    { on = "O",           run = "arrow next",                desc = "Move cursor down" },
    { on = "~",           run = "help",                      desc = "Open Help" },
]

[tasks]
keymap = [
    { on = "w",           run = "close",                     desc = "Close task manager" },
    { on = "y",           run = "arrow prev",                desc = "Move cursor up" },
    { on = "i",           run = "arrow next",                desc = "Move cursor down" },
    { on = "<Enter>",     run = "inspect",                   desc = "Inspect the task" },
    { on = "C-c",         run = "cancel",                    desc = "Cancel the task" },
    { on = "~",           run = "help",                      desc = "Open Help" },
]

[spot]
keymap = [
    { on = "<Esc>",       run = "close",                     desc = "Close the spot" },
    { on = "<S-Tab>",     run = "arrow prev",                desc = "Previous Line" },
    { on = "<Tab>",       run = "arrow next",                desc = "Next Line" },
	  { on = "y",           run = "swipe prev",                desc = "Swipe to previous file" },
	  { on = "i",           run = "swipe next",                desc = "Swipe to next file" },
    { on = "c",           run = "copy cell",                 desc = "Copy selected cell" },
    { on = "~",           run = "help",                      desc = "Open Help" },
]

[pick]
keymap = [
    { on = "<Esc>",       run = "close",                     desc = "Cancel pick" },
    { on = "<Enter>",     run = "close --submit",            desc = "Submit the pick" },
    { on = "<S-Tab>",     run = "arrow prev",                desc = "Previous option" },
    { on = "<Tab>",       run = "arrow next",                desc = "Next option" },
    { on = "~",           run = "help",                      desc = "Open Help" },
]

[cmp]
keymap = [
    { on = "<Esc>",       run = "close",                     desc = "Cancel completion" },
    { on = "<Enter>",     run = "close --submit",            desc = "Submit the completion" },
    { on = "<S-Tab>",     run = "arrow prev",                desc = "Move cursor up" },
    { on = "<Tab>",       run = "arrow next",                desc = "Move cursor down" },
    # { on = "", run = [ "close --submit", "input:close --submit" ], desc = "Submit the completion and input" },
    { on = "~",           run = "help",                      desc = "Open Help" },
]

[help]
keymap = [
	{ on = "<Esc>",         run = "escape",                    desc = "Clear the filter, or hide the help" },
	{ on = "<C-c>",         run = "close",                     desc = "Hide the help" },
	{ on = "<S-Tab>",       run = "arrow prev",                desc = "Previous line" },
	{ on = "<Tab>",         run = "arrow next",                desc = "Next line" },
	{ on = "f",             run = "filter",                    desc = "Filter help items" },    
]
